name: azkar
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.14.8+149

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_login_facebook: ^1.4.1
  http: ^1.0.0
  auth_buttons: ^3.0.2
  flutter_login: ^3.0.0
  flutter_secure_storage: ^9.0.0
  flare_flutter: ^3.0.2
  progress_state_button: ^1.0.1
  sprintf: ^7.0.0
  flutter_localization: any
  firebase_core: ^2.28.0
  firebase_messaging: ^14.8.0
  shared_preferences: ^2.0.5
  optional: ^6.1.0+1
  confetti: ^0.7.0
  flutter_slidable: ^3.1.0
  feature_discovery: ^0.14.0
  share_plus: ^8.0.2
  toggle_switch: ^2.3.0
  introduction_screen: ^3.1.14
  in_app_review: ^2.0.4
  crisp: ^0.3.1
  crypto: ^3.0.1
  shimmer: ^3.0.0
  flutter_ringtone_player: ^4.0.0+2
  auto_size_text: ^3.0.0
  clear_all_notifications: ^1.0.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.0
  googleapis: ^13.1.0
  flutter_signin_button: ^2.0.0
  flutter_local_notifications: ^17.0.0
  numberpicker: ^2.1.2
  the_apple_sign_in: ^1.1.1
  device_info_plus: ^10.0.1
  url_launcher: ^6.1.0
  synchronized: ^3.0.0+2
  firebase_analytics: ^10.10.0
  intl: ^0.18.1
  odometer: ^3.0.0
  permission_handler: ^11.3.1
  collection: any


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/mountains.jpg
    - assets/images/otp.flr
    - assets/images/verify.png
    - assets/images/icon.png
    - assets/images/logo.png
    - assets/images/logo_fore.png
    - assets/images/username.png
    - assets/images/add_friend.png
    - assets/images/challenge.png
    - assets/images/friends.png
    - assets/gts-root-r1.crt
    - assets/quran.txt
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf
    - family: arabic
      fonts:
        - asset: assets/fonts/arabic-Regular.ttf
        - asset: assets/fonts/arabic-Bold.ttf
        - asset: assets/fonts/arabic-Medium.ttf
        - asset: assets/fonts/arabic-SemiBold.ttf
        - asset: assets/fonts/arabic-VariableFont_wght.ttf
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto-Black.ttf
        - asset: assets/fonts/roboto-BlackItalic.ttf
        - asset: assets/fonts/roboto-Bold.ttf
        - asset: assets/fonts/roboto-BoldItalic.ttf
        - asset: assets/fonts/roboto-Italic.ttf
        - asset: assets/fonts/roboto-Light.ttf
        - asset: assets/fonts/roboto-LightItalic.ttf
        - asset: assets/fonts/roboto-Medium.ttf
        - asset: assets/fonts/roboto-MediumItalic.ttf
        - asset: assets/fonts/roboto-Regular.ttf
        - asset: assets/fonts/roboto-Thin.ttf
    - family: uthmanic
      fonts:
        - asset: assets/fonts/uthmanic.otf
