name: Code Formatter and Analayzer

on:
  pull_request:
  push:
      branches:
        - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: subosito/flutter-action@v1
      with:
        flutter-version:  '2.5.3'
        channel: 'stable'
    
    - run: flutter format --set-exit-if-changed .
    - run: flutter analyze .
