name: Notifications Enabled

on:
  push:
      branches:
        - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - run: |
        found=($(grep "^apply plugin: 'com.google.gms.google-services'" android/app/build.gradle | wc -l))
        found || exit 1
        exit 0
