name: Notifications Enabled

on:
  push:
      branches:
        - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - run: |
          ls
          found=($(grep "^apply plugin: 'com.google.gms.google-services'" android/app/build.gradle | wc -l))
          [ found == 1 ] || exit 1
          exit 0
